### ISSUE TITLE
Contribute to the project

### ISSUE THREAD

**Issue by NguyenMinhDuc163** [LuongLuyen/git-flow#4]
![meme-la-gi-8](https://github.com/user-attachments/assets/7ccce4bf-0fef-471b-97ee-a4f74b97c76c)

**Comment by LuongLuyen** [comment]
@NguyenMinhDuc163 ngài muốn góp vui hả

**Comment by NguyenMinhDuc163** [comment]
add vào ngay và luôn chứ
